/* DROP todas las tablas para borrar cualquiera
con nombre similar */
DROP TABLE TDIRORQ;
DROP TABLE CONOBR;
DROP TABLE CONSOLI;
DROP TABLE OBRASOLI;
DROP TABLE TCONCIER;
DROP TABLE TORQUES;
DROP TABLE TDIRECT;
DROP TABLE TOBRA;
DROP TABLE TCOMPOS;
DROP TABLE TSOLIS;

/* EN TODAS LAS TABLAS RELACIONALES HAY UNA CLAVE
COMPUESTA FORMADA POR 2 CLAVES PRICIPALES QUE SON
A SU TAMBIEN CLAVES FORANEAS DE LAS DOS TABLAS
QUE RELACIONAN, EN EL CASO DE LA TABLA RELACIONAL
ENTRE DIRECTORES Y ORQUESTA ESTA SOLO CONTIENE LOS
CODIGOS DE LOS DIRECTORES INVITADOS PARA PODER
DIFERENCIARLOS DE LOS TITULARES */
/* TODAS LAS CLAVES ESTAN ON DELETE CASCADE PARA
MANTENER LA INTEGRIDAD REFERENCIAL ENTRE CLAVE
PRINCIPAL Y FORANEA*/

/* TABLA DIRECTORES */
CREATE TABLE TDIRECT (
  NUMDIR NUMBER(3) PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  DIRECCION VARCHAR2(100),
  FECNA DATE,
  TITULAR VARCHAR2(2)
);
/* TABLA ORQUESTAS */
CREATE TABLE TORQUES(
    NUMORQ NUMBER(3) PRIMARY KEY,
    NUMDIR NUMBER(3),
    NOMBRE VARCHAR2(80),
    DIRECCION VARCHAR2(100),
    TEMPORADA VARCHAR2(80),
    FECIN DATE,
    CONSTRAINT FK_NUMDIRRR
      FOREIGN KEY(NUMDIR)
        REFERENCES TDIRECT(NUMDIR) ON DELETE CASCADE
);
/* TABLA RELACIONAL DIRECTORES/ORQUESTA*/
CREATE TABLE TDIRORQ(
  NUMDIR NUMBER(3),
  NUMORQ NUMBER(3),
  PRIMARY KEY(NUMDIR,NUMORQ),
  CONSTRAINT FK_NUMDIR
    FOREIGN KEY(NUMDIR)
      REFERENCES TDIRECT(NUMDIR) ON DELETE CASCADE,
  CONSTRAINT FK_NUMORQ
    FOREIGN KEY(NUMORQ)
      REFERENCES TORQUES(NUMORQ) ON DELETE CASCADE
);
/* TABLA CONCIERTOS */
CREATE TABLE TCONCIER(
  NUMCON NUMBER(3) PRIMARY KEY,
  NUMORQ NUMBER(3),
  NOMBRE VARCHAR2(80),
  CONSTRAINT FK_NUMORQUES
    FOREIGN KEY (NUMORQ)
      REFERENCES TORQUES(NUMORQ) ON DELETE CASCADE
);
/* TABLA COMPOSITORES */
CREATE TABLE TCOMPOS(
  NUMCOMP NUMBER(3) PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  FECNA DATE,
  DECDEP DATE
);
/* TABLA OBRAS */
CREATE TABLE TOBRA(
  NUMOBR NUMBER(3) PRIMARY KEY,
  TITULO VARCHAR2(80),
  NUMCOMP NUMBER(3),
  CONSTRAINT FK_NUMCOMP
    FOREIGN KEY(NUMCOMP)
      REFERENCES TCOMPOS(NUMCOMP) ON DELETE CASCADE
);
/* TABLA SOLISTAS */
CREATE TABLE TSOLIS(
  NUMSOLIS NUMBER(3) PRIMARY KEY,
  NOMBRE VARCHAR(80),
  FECNA DATE,
  INSTRUMENTO VARCHAR2(80)
);
/* TABLA RELACIONAL CONCIERTOS/OBRAS */
CREATE TABLE CONOBR(
  NUMCON NUMBER(3),
  NUMOBR NUMBER(3),
  PRIMARY KEY(NUMCON,NUMOBR),
  CONSTRAINT FK_NUMCON
    FOREIGN KEY(NUMCON)
      REFERENCES TCONCIER(NUMCON) ON DELETE CASCADE,
  CONSTRAINT NUMSOLI
    FOREIGN KEY(NUMOBR)
      REFERENCES TOBRA(NUMOBR) ON DELETE CASCADE
);
/* TABLA REALCIONAL CONCIERTOS/SOLISTAS */
CREATE TABLE CONSOLI(
  NUMCON NUMBER(3),
  NUMSOLI NUMBER(3),
  PRIMARY KEY(NUMCON,NUMSOLI),
  CONSTRAINT FK_NUMCONC
    FOREIGN KEY(NUMCON)
      REFERENCES TCONCIER(NUMCON) ON DELETE CASCADE  ,
  CONSTRAINT FK_NUMSOLI
    FOREIGN KEY(NUMSOLI)
      REFERENCES TSOLIS(NUMSOLIS) ON DELETE CASCADE
);
/* TABLA RELACIONAL OBRAS/SOLISTAS */
CREATE TABLE OBRASOLI(
  NUMOBR NUMBER(3),
  NUMSOLIS NUMBER(3),
  PRIMARY KEY(NUMOBR,NUMSOLIS),
  CONSTRAINT FK_NUMOBR
    FOREIGN KEY(NUMOBR)
      REFERENCES TOBRA(NUMOBR) ON DELETE CASCADE,
  CONSTRAINT FK_NUMSOLIS
    FOREIGN KEY(NUMSOLIS)
      REFERENCES TSOLIS(NUMSOLIS) ON DELETE CASCADE
);
