ROLLBACK;

/* Insertar tabla directores */
INSERT INTO TDIRECT VALUES(1,'PEPE ANTONIO','MADRID','06/JAN/98','NO');
INSERT INTO TDIRECT VALUES(2,'FRANCISCO JAVIER','NEW YORK','20/FEB/85','SI');
INSERT INTO TDIRECT VALUES(3,'AYOUB ALAHUAKBAR','MARRAKECH','11/DEC/75','SI');
INSERT INTO TDIRECT VALUES(4,'IVAN VASILIEVICH','SAN PETERSBURGO','25/AUG/35','SI');
INSERT INTO TDIRECT VALUES(5,'JONH PRICE','LONDRES','07/DEC/66','SI');
INSERT INTO TDIRECT VALUES(6,'LUIS LORENZO','BARCELONA','01/JAN/88','NO');
INSERT INTO TDIRECT VALUES(7,'PEDRO MACAQUINO','RIO DE JANEIRO','25/MAY/55','NO');
INSERT INTO TDIRECT VALUES(8,'CHEEKI BREEKI','TARKOV','04/NOV/87','SI');
INSERT INTO TDIRECT VALUES(9,'GERALDO RIVERAS','MURCIA','19/SEP/61','SI');
INSERT INTO TDIRECT VALUES(10,'XUEHUAPIAOPIAO','PEKIN','30/OCT/95','SI');

/* INSERTAR TABLA ORQUESTAS */
INSERT INTO TORQUES VALUES(1,8,'TARKOV ORCHESTRA','TARKOV','INVIERNO','12/JAN/01');
INSERT INTO TORQUES VALUES(2,10,'SOCIALSCREDITS','PEKIN','VERANO','05/SEP/00');
INSERT INTO TORQUES VALUES(3,9,'ORQUESTA MURCIANA','MURCIA','OTOÑO','01/MAY/99');
INSERT INTO TORQUES VALUES(4,5,'OI MATE MUSICAL GROUP','LONDRES','INVIERNO','17/NOV/04');
INSERT INTO TORQUES VALUES(5,4,'SIBERIAN VACATIONS','SIBERIA','INVIERNO','26/DEC/91');
INSERT INTO TORQUES VALUES(6,3,'BOOM','JERUSALEM','PRIMAVERA','31/JUL/98');
INSERT INTO TORQUES VALUES(7,2,'BACAN NEW YORK','NEW YORK','INVIERNO','14/OCT/05');



/* INSERTAR TABLA RELACIONAL DIRECTORES/ORQUESTAS SOLO NOS TITULARES*/
INSERT INTO TDIRORQ VALUES(1,1);
INSERT INTO TDIRORQ VALUES(6,7);
INSERT INTO TDIRORQ VALUES(7,6);


/* INSERTAR TABLA CONCIERTOS */
INSERT INTO TCONCIER VALUES(1,1,'WELCOME TO TARKOV');
INSERT INTO TCONCIER VALUES(2,2,'CHINPINEN JONH XINA');
INSERT INTO TCONCIER VALUES(3,3,'BUSCANDO MURCIA');
INSERT INTO TCONCIER VALUES(4,4,'BEANS FOR BRAKFAST');
INSERT INTO TCONCIER VALUES(5,5,'GULAGED');
INSERT INTO TCONCIER VALUES(6,6,'COMPOSITION 4');
INSERT INTO TCONCIER VALUES(7,7,'THE NEW YORK MENOL');

/*INSERTAR TABLA COMPOSITORES */
INSERT INTO TCOMPOS VALUES(1,'ALBERTO THOTOH','19/JAN/70','07/FEB/80');
INSERT INTO TCOMPOS VALUES(2,'JASON ARGONAUTA','07/AUG/80','10/MAY/95');
INSERT INTO TCOMPOS VALUES(3,'CARLO MAGNO','04/JUL/60','02/OCT/75');
INSERT INTO TCOMPOS VALUES(4,'ANTONIO MACEO','07/DEC/55','28/NOV/71');
INSERT INTO TCOMPOS VALUES(5,'FERNANDO EUGENIO','21/JUN/81','20/MAY/00');
INSERT INTO TCOMPOS VALUES(6,'GERMAN ORSOL','9/JUN/88','01/MAY/02');
INSERT INTO TCOMPOS VALUES(7,'DARIO MEHERDAD','29/AUG/75','14/JAN/95');

/* INSERTAR TABLA OBRAS */
INSERT INTO TOBRA VALUES(1,'EL LAGO DE LOS CISNES',1);
INSERT INTO TOBRA VALUES(2,'EL CASCANUECES',2);
INSERT INTO TOBRA VALUES(3,'ODA A MURCIA',3);
INSERT INTO TOBRA VALUES(4,'LA NIEVE DE VACACIONES',4);
INSERT INTO TOBRA VALUES(5,'DABAI DABAI DA',5);
INSERT INTO TOBRA VALUES(6,'BACAN BACAN NEW YOR',6);
INSERT INTO TOBRA VALUES(7,'EL POLLO SIN CABEZA',7);

/*INSERTAR TABLA SOLISTA */
INSERT INTO TSOLIS VALUES(1,'RIGOBERTO RONDON','21/DEC/90','TAMBOR');
INSERT INTO TSOLIS VALUES(2,'JOSE JUAQUIN','01/MAY/80','TUBA');
INSERT INTO TSOLIS VALUES(3,'DANIEL CHICO','16/SEP/80','TROMPETA');
INSERT INTO TSOLIS VALUES(4,'NORBERTO RODRIGUEZ','31/DEC/72','VIOLIN');
INSERT INTO TSOLIS VALUES(5,'ELIO CALDERON','14/OCT/91','VIOLA');
INSERT INTO TSOLIS VALUES(6,'YANH MARCOS','06/AUG/83','TROMBON');
INSERT INTO TSOLIS VALUES(7,'DIEGO CARDENAS','30/JUN/77','PIANO');

/* INSERTAR TABLA RELACIONAL CONCIERTO/OBRA */
INSERT INTO CONOBR VALUES(1,5);
INSERT INTO CONOBR VALUES(2,1);
INSERT INTO CONOBR VALUES(3,3);
INSERT INTO CONOBR VALUES(4,2);
INSERT INTO CONOBR VALUES(5,4);
INSERT INTO CONOBR VALUES(6,7);
INSERT INTO CONOBR VALUES(7,6);

/* INSERTAR TABLA RELACIONAL CONCIERTO/SOLISTA */
INSERT INTO CONSOLI VALUES(1,1);
INSERT INTO CONSOLI VALUES(2,2);
INSERT INTO CONSOLI VALUES(3,3);
INSERT INTO CONSOLI VALUES(4,4);
INSERT INTO CONSOLI VALUES(5,5);
INSERT INTO CONSOLI VALUES(6,6);
INSERT INTO CONSOLI VALUES(7,7);

/* INSERTAR TABLA RELACIONAL OBRA/SOLISTA */
INSERT INTO OBRASOLI VALUES(1,1);
INSERT INTO OBRASOLI VALUES(2,2);
INSERT INTO OBRASOLI VALUES(3,3);
INSERT INTO OBRASOLI VALUES(4,4);
INSERT INTO OBRASOLI VALUES(5,5);
INSERT INTO OBRASOLI VALUES(6,6);
INSERT INTO OBRASOLI VALUES(7,7);
COMMIT;
SELECT * FROM TDIRECT

