/* Creacion de tabla */
create table prueba(
ident number(10),
nombre varchar2(20),
apellido varchar2(20),
ideusu varchar2(15),
salario number(10)
);
SELECT * from prueba;

/* 3-4-5insercion de registros */
/* INSERT INTO prueba
VALUES (1, 'Sergio', 'Benito', 'SERBEN', 900); */
INSERT INTO prueba
VALUES (2, 'Javier', 'NAVAS', 'JAVNAV', 1000);
INSERT INTO prueba
VALUES (3, 'ANTONIO', 'CAZALLA', 'ANTCAZ', 990);
INSERT INTO prueba
VALUES (4, 'SAMUEL', 'DIAZ', 'SAMDIA', 1130);
INSERT INTO prueba
VALUES (5, 'FERNANDO', 'GOMEZ', 'FERGOM', 900);
INSERT INTO prueba
VALUES (6, 'CARLOS', 'JUAREZ', 'CARJU', 1500);
INSERT INTO prueba
VALUES (7, 'JUANJO', 'MORALES', 'JUAMOR', 1200);
INSERT INTO prueba
VALUES (8, 'GUSTAVO', 'MORENO', 'GUSMOR', 1050);
INSERT INTO prueba
VALUES (9, 'ANGELES', 'RODRIGUEZ', 'ANGROD', 1225);
/* 7 */
UPDATE prueba
SET apellido = 'GONZALES'
WHERE IDENT = 3;

/* 8 */
UPDATE prueba
SET salario = 960
WHERE salario <= 950;

/* 10 */
DELETE FROM PRUEBA
WHERE nombre IN ('GUSTAVO');
SELECT * FROM PRUEBA;
COMMIT;

/* 13 insercion registros */
INSERT INTO PRUEBA
VALUES (10,'EVA','RODRIGUEZ', 'EVAROD', 1090);
INSERT INTO PRUEBA
VALUES (11,'RAQUEL','SANCHEZ', 'RAQSAN', 1090);
INSERT INTO PRUEBA
VALUES (12,'RAUL','SOLA', 'RAUSOL', 1310);

/* 15 */
SAVEPOINT INTERMEDIO;
SAVEPOINT salvado;

/* 16-17 */
DELETE FROM PRUEBA;
SELECT * FROM PRUEBA;

/* 18 */
ROLLBACK TO SAVEPOINT salvado;
ROLLBACK;

/* 20 */
COMMIT;

/* 21 */
SELECT * FROM TDEPTO;
DELETE FROM TDEPTO
WHERE NUMDE = 123;
INSERT INTO TDEPTO
VALUES(123,10,350,'F',4,120,'PLANIFICACION');

/* 22 */
SELECT * FROM TEMPLE;
INSERT INTO TEMPLE
VALUES (125,120,350,NULL,SYSDATE,2000,NULL,1,'GARCES, CONSTANTINO');

/* 23 */
INSERT INTO TEMPLE2
SELECT * FROM TEMPLE
WHERE FECIN > '12-DEC-1970';
SELECT * FROM TEMPLE2;
DELETE FROM TEMPLE2;

/* 24 */
DELETE FROM TEMPLE
WHERE NOMEM LIKE ('GARCES%');

/* 25 */
DELETE FROM TEMPLE
WHERE SALAR > (SELECT AVG(A.SALAR)
                FROM TEMPLE A
                JOIN TEMPLE B ON A.NUMDE = B.NUMDE );